//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsVehicles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_ClassVehicles
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_ClassVehicles()
        {
            this.TB_Vehicles = new HashSet<TB_Vehicles>();
        }
    
        public int IdClassVehicle { get; set; }
        public string ClassVehicle { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vehicles> TB_Vehicles { get; set; }
    }
}
