//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsVehicles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Manufacturers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Manufacturers()
        {
            this.TB_Vehicles = new HashSet<TB_Vehicles>();
        }
    
        public int IdManufacturer { get; set; }
        public int CountryId { get; set; }
        public string NameManufacturer { get; set; }
        public Nullable<System.DateTime> DateFoundation { get; set; }
        public byte[] Logo { get; set; }
        public bool Active { get; set; }
    
        public virtual TB_Countries TB_Countries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Vehicles> TB_Vehicles { get; set; }
    }
}
