//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsVehicles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Vehicles
    {
        public int IdVehicle { get; set; }
        public int ClassVehicleId { get; set; }
        public int ManufacturerId { get; set; }
        public int TypeId { get; set; }
        public string Model { get; set; }
        public int Year { get; set; }
        public Nullable<bool> InProduction { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual TB_ClassVehicles TB_ClassVehicles { get; set; }
        public virtual TB_Manufacturers TB_Manufacturers { get; set; }
        public virtual TB_Types TB_Types { get; set; }
    }
}
