//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wsVehicles.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BD_VEHICLESEntities : DbContext
    {
        public BD_VEHICLESEntities()
            : base("name=BD_VEHICLESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TB_ClassVehicles> TB_ClassVehicles { get; set; }
        public virtual DbSet<TB_Countries> TB_Countries { get; set; }
        public virtual DbSet<TB_Manufacturers> TB_Manufacturers { get; set; }
        public virtual DbSet<TB_Types> TB_Types { get; set; }
        public virtual DbSet<TB_Vehicles> TB_Vehicles { get; set; }
    }
}
